{"uuid": "dd818e1b-f2c6-43c4-8b0e-b8b524f69a7c", "children": ["0339fd19-0af8-49dc-88c1-8af3da82368b"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: Requested environment is not available\n\n", "trace": "  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\conftest.py\", line 38, in browser\n    driver = webdriver.Remote(\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1681759874340, "stop": 1681759874364}], "start": 1681759874340, "stop": 1681759874470}